@extends('layouts.landing-layout')


@section('head')
	<title>About | VotePen</title>
	<meta property="og:type" content="article" />
	<meta property="og:title" content="About | VotePen" />
	<meta property="og:url" content="{{ config('app.url') }}/about" />
	<meta property="og:site_name" content="VotePen" />

	<meta name="twitter:card" content="summary" />
	<meta name="twitter:site" content="@votepen" />
	<meta name="twitter:title" content="About | VotePen" />

	<meta name="description" content="We are a small team of developers risen from the world of . We believe in an open and modern Internet. VotePen's mission is to give people the power to share their content with not just their friends but the world and interact in real-time."/>
	<meta property="og:description" content="We are a small team of developers risen from the world of open-source. We believe in an open and modern Internet. VotePen's mission is to give people the power to share their content with not just their friends but the world and interact in real-time." />
	<meta name="twitter:description" content="We are a small team of developers risen from the world of open-source. We believe in an open and modern Internet. VotePen's mission is to give people the power to share their content with not just their friends but the world and interact in real-time." />
	<meta property="og:image" content="https://cdn.jsdelivr.net/npm/votepen@12.0.0/imgs/votepen-og.png">
	<meta name="twitter:image" content="https://cdn.jsdelivr.net/npm/votepen@12.0.0/imgs/votepen-og.png" />

	<script type="application/ld+json">
	 {
		 "@context": "http://schema.org",
		 "@type": "WebSite",
		 "url": "https://votepen.co",
		 "name": "VotePen",
			"publisher": {
			 "@type": "Organization",
		  "logo": {
			  "@type": "ImageObject",
				 "url": "https://cdn.jsdelivr.net/npm/votepen@12.0.0/imgs/votepen.svg",
				 "name": "VotePen",
				 "height": "457",
				 "width": "457"
				}
			},
		 "sameAs": [
			 "https://www.facebook.com/votepen/",
			 "https://twitter.com/votepen"
		 ],
		 "potentialAction": {
			"@type": "SearchAction",
			"target": "https://votepen.com/?search={search_term_string}",
			"query-input": "required name=search_term_string"
		 }
	 }
	 </script>
@endsection


@section('content')
	<div class="about-wrapper mobile-padding">
		<div class="align-center">
			<img src="https://cdn.jsdelivr.net/npm/votepen@12.0.0/imgs/votepen-logo.png" alt="VotePen" class="about-logo margin-bottom-1">

			<h1 class="title">
				Social Bookmarking to Stay Updated!
			</h1>
		</div>


		<p>
			VotePen bridges communities and individuals with ideas, the latest digital trends, and breaking news to stay updated. Our mission is to give people the power to share their content with not just their friends but the world and interact in real-time.
		</p>
		<div class="boxes-container">
			<div class="box-item">
				<h3>
					<a href="http://php.net/" rel="nofollow">
						<img src="https://cdn.jsdelivr.net/npm/votepen@12.0.0/landing/about/share.png" alt="Share">
					</a>
				</h3>

				<div>
					<p>
						Anyone can create a channel on nearly any topic imaginable. Each channel is independently moderated by volunteer users. Community members can share content including stories, links, and images.
					</p>
				</div>
			</div>

			<div class="box-item">
				<h3>
					<a href="http://php.net/" rel="nofollow">
						<img src="https://cdn.jsdelivr.net/npm/votepen@12.0.0/landing/about/vote.png" alt="Vote">
					</a>
				</h3>

				<div>
					<p>
						The global VotePen community votes on which stories and discussions are important by casting upvotes or downvotes. The most interesting, funniest, impactful channel will be on top.
					</p>
				</div>
			</div>

			<div class="box-item">
				<h3>
					<a href="http://php.net/" rel="nofollow">
						<img src="https://cdn.jsdelivr.net/npm/votepen@12.0.0/landing/about/discuss.png" alt="Discuss">
					</a>
				</h3>

				<div>
					<p>
						Penners can comment on any post on VotePen. Comments are often the best part about VotePen content—they provide additional information, vigorous discussion, context, and often humor.
					</p>
				</div>
			</div>
		</div>
		<br>
		<h2 class="title">Users are voters and penners</h2>
		<p>
			On VotePen users are in charge. They get to decide what deserves more attention by voting. We call authors as "Penners".
		</p>

		<br>
		<h2 class="title">What is VotePen?</h2>
		<p>
			<p>VotePen™ officially launched in January 2018 as a media aggregator website featuring user-posted content.</p>
			
			<p>VotePen initially started as a hobby project by a sophomore student in India. Due to the recent interest generated by the online community, this has evolved from hobby into full-fledged desire to create the website that will become the place where you can "Stay Updated"</p>
		</p>
		
		<h2 class="title">Hey... you look like that other site!</h2>
		<p>
			<p>All cars have four wheels. Does that mean that every car is the same?</p>
		</p>		
		<br>
	</div>


@endsection